### ISSUE TITLE
Add bindings package to the Julia General Registry

### ISSUE THREAD

**Issue by IshaanDesai** [precice/PreCICE.jl#18]
The julia-bindings should be added to the [Julia General Registry](https://github.com/JuliaRegistries/General) so that they can be installed using the `add` command using `Pkg`.

**Comment by erikscheurer** [comment]
The easiest way would be to install the [Registrator bot](https://github.com/JuliaRegistries/Registrator.jl#install-registrator) in this Repository, then we would only have to tag the bot in a github issue and the bot would automatically add the Package to the Registry within a few days. New releases would also be done this way in combination with the [TagBot](https://github.com/precice/julia-bindings/blob/main/.github/workflows/TagBot.yml)
We should change the version of the Package in the [Project.toml](https://github.com/precice/julia-bindings/blob/46869316f076fcb1e05f203ea7a9a903d8bacc14/Project.toml#L4)
Should we do this before the next milestone with a pre-release version, or only with the first release?

**Comment by erikscheurer** [comment]
A few more comments on the above mentioned bots. 
The Registrator bot takes the version number from the [Project.toml] and opens a pull request at the Julia General Registry when instructed by a comment (`@JuliaRegistrator register`) on the commit/branch that we want to release. [This](https://github.com/JuliaRegistries/Registrator.jl/issues/61) is an example. A moderator will have a look at it and maybe leave some comments if we should change something. Otherwise, the process doesn't require input from our side. 
The TagBot automate the process of a github release every time the Registrator bot is called. And is also [able to](https://github.com/marketplace/actions/julia-tagbot) generate changelogs with the new release.

**Comment by IshaanDesai** [comment]
Okay, the whole strategy looks very streamlined. Once we have sorted out all the issues that we want to address in the upcoming release, lets do a Pre-release and try out this whole workflow. Once we know it works we can deploy it on the actual release `v2.4.0.0`

**Comment by IshaanDesai** [comment]
Done in fist experimental release https://github.com/precice/PreCICE.jl/releases/tag/v0.0.1
