### ISSUE TITLE
Deploy a code formatter for the bindings

### ISSUE THREAD

**Issue by IshaanDesai** [precice/PreCICE.jl#24]
Currently we do not have a formatter which is governing the code styling for the bindings. We should investigate which is the most standard format to write Julia code and accordingly standardize the code and also if possible deploy a formatting action which will check if code added in the future is properly formatted or not.

One option could be the [JuliaFormatter](https://juliapackages.com/p/juliaformatter) which is also [used in VS Code](https://www.julia-vscode.org/docs/dev/userguide/formatter/).

**Comment by erikscheurer** [comment]
There is a official [style guide](https://docs.julialang.org/en/v1/manual/style-guide/) but no way to enforce it as it mainly refers to how to use functionality and not the formatting.
The JuliaFormatter you mentioned already has included github actions for [checking the format](https://github.com/julia-actions/julia-format/blob/master/workflows/format_check.yml) and for a periodic [format pull request](https://github.com/julia-actions/julia-format/blob/master/workflows/format_pr.yml).
We can also take a look at the [guildelines for Julia base developers](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#general-formatting-guidelines-for-julia-code-contributions). 
Other than those I didn't find a general Format or Formatter that is used widely. I'm even a little surprised, because the biggest packages found on [Juliahub](https://juliahub.com/ui/Packages) don't use a formatter workflow.
